### ISSUE TITLE
Any plan to update map to include บึงกาฬ, the latest province?

### ISSUE THREAD

**Issue by kristw** [apisit/thailand.json#1]

**Comment by apisit** [comment]
oh long time since this.
The shapefile I have Bueng Kan is still an Amphoe in Nong Khai. I guess I could just move it to be in Administrative Level 1. However, I am not sure that its shape area is accurate. 
![shape file](http://i.imgur.com/41wS0mu.png)

if you have the accurately shaped one, pull request is very welcome.

**Comment by kristw** [comment]
I don't have latest shapefile though. Seems like it came from more than one Amphoe. According to wikipedia,

> "เนื่องจากจังหวัดหนองคายเป็นจังหวัดที่มีท้องที่ติดชายแดน และมีลักษณะภูมิประเทศเป็นแนวยาว ทำให้การติดต่อระหว่างอำเภอที่ห่างไกลและจังหวัดเป็นไปด้วยความยากลำบาก และใช้ระยะเวลาในการเดินทางมากเกินควร ดังนั้น เพื่อประโยชน์ในการจัดระเบียบการปกครอง การรักษาความมั่นคง และการอำนวยความสะดวกให้แก่ประชาชนในท้องที่ สมควรแยก **อำเภอบึงกาฬ อำเภอเซกา อำเภอโซ่พิสัย อำเภอบุ่งคล้า อำเภอบึงโขงหลง อำเภอปากคาด อำเภอพรเจริญ และอำเภอศรีวิไล** จังหวัดหนองคาย ออกจากการปกครองของจังหวัดหนองคาย รวมตั้งขึ้นเป็นจังหวัดบึงกาฬ จึงจำเป็นต้องตราพระราชบัญญัตินี้"

https://th.wikipedia.org/wiki/จังหวัดบึงกาฬ

The reason I thought about this was this project [gridmap-layout-thailand](https://github.com/kristw/gridmap-layout-thailand). I had to add this province manually. Haha.

**Comment by apisit** [comment]
here you go @kristw Bueng Kan is here #2 Thanks @adkdev 🙏
